### ISSUE TITLE
Meeting Agenda 21 August 2019

### ISSUE THREAD

**Issue by AlexEne** [rust-gamedev/wg#38]
Opening this for our next meeting.

**Comment by Lokathor** [comment]
Within this next 2 weeks we will attempt to have some progress on a "State Of The Ecosystem" document. If not 100% complete, at least something good enough to merge into the repo and show off in an incomplete state.

* WIP PR: https://github.com/rust-gamedev/wg/pull/11

**Comment by Osspial** [comment]
I'd like to set a hard deadline of releasing an initial version of `raw-window-handle` by the time the next meeting happens. That'll let us talk about how ecosystem integration is going, and any potential pitfalls in the design that weren't foreseen.

**Comment by Lokathor** [comment]
Let's release at least the day before so that people have an evening to try it out before the meeting.

**Comment by Lokathor** [comment]
Agenda Update:
* `raw-window-handle` is out and supported by `winit` and `glutin`.
* Issues have been filed on various graphical repos for them to support this new API

So now the discussion is "how much have the graphics caught up yet?"

**Comment by Lokathor** [comment]
@kvark: My work schedule changed so I'll have to join the meeting from my phone from here on basically. @alex also said in Discord just now that they won't be able to attend this one.

Could you direct today's meeting, and also possibly record it?

**Comment by kvark** [comment]
@Lokathor Ok, sure. It's probably going to be short :)

**Comment by kvark** [comment]
Attendance:
- @kvark
- @Lokathor 
- @grovesNL
- @msiglreith

**Comment by kvark** [comment]
Very brief notes from the meeting:

### Ecosystem guide

Can't do it while staying opinionated. Instead, we need to improve AreWeGameYet organization in multiple ways:
  1. Indicate the "liveness": if something is outdated versus recently updated
  2. Classify with features that we (the community and the working group) all agree on. Modifying the feature labels would need to be peer-reviewed so that the classification stays objective at large.
  3. Give a clue about the tech stack ("main" dependencies) as well as compatibility (e.g. "this works with winit").

Another complementary approach is to try mapping the ecosystem crates to [the gamedev map](http://hightalestudios.com/wordpress/wp-content/uploads/2017/03/jaKUP.png), which would allow us to identify missing pieces.

_Remco_ (what is the github handle?) volunteered to champion this work, or at least work on the design of these improvements.

### Raw Window Handle

gfx-rs and wgpu-rs integration is on the way (publishing today/tomorrow).

Has known 2 issues:
  1. GL init requires more than just a window handle. It's not possible to init the context on an existing window handle. (link to issue by @omni-viral ?). @Lokathor expressed interest in spawning the discussion about this.
  2. Metal initialization is canonically done via `CAMetalLayer` which isn't directly exposed by the raw-window-handle, see https://github.com/rust-windowing/raw-window-handle/issues/14

### Connection to the core Rust team

We need a place to share all the requests to the language and standard library. It could be done a markdown file in this repo. _Philip_ (github handle?) will follow up with a PR with the initial list they have.

**Comment by Wodann** [comment]
> _Remco_ (what is the github handle?)
@Wodann

**Comment by Lokathor** [comment]
Kev said they recorded the meeting and they'll post the link here once it's uploaded

**Comment by kabergstrom** [comment]
Recording of the meeting
https://www.youtube.com/watch?v=P-X_V43z3Dg

**Comment by aclysma** [comment]
> Philip (github handle?)
@aclysma

**Comment by JeanMertz** [comment]
> Recording of the meeting

Quick question: can we get a global rust gamedev account on YouTube so when different people do the recording, it still ends up on the same place, and people can follow that account for notifications?

Such a channel could also include other videos related to rust game dev (segregated in different playlists).

This is similar to how other WGs are doing this.

**Comment by Lokathor** [comment]
We could and should, the biggest problem is that a 1hr recording is about 1gb, so moving the videos around is a bit of a problem. We can probably just make an account and share the credentials as necessary so that whoever recorded each one can put it directly on YouTube.

**Comment by minecrawler** [comment]
Just to throw in options: there are programs which can reduce the size drastically easily. [Let me quote](https://community.amethyst.rs/t/amethyst-loading-screen-animation-with-sound/1017/3) [Handbreak](https://handbrake.fr/) for example :)
