### ISSUE TITLE
Watching this working group

### ISSUE THREAD

**Issue by Kinrany** [rust-gamedev/wg#66]
I'd like to follow this working group and be up to date about the progress you make, but I don't want to be notified of every conversation.

Since you're using Github anyway, I wonder if it would make sense to use tags and "releases only" to notify of the larger milestones.

**Comment by 17cupsofcoffee** [comment]
Any big news usually gets published in the [monthly newsletter](https://rust-gamedev.github.io/2019/10/05/newsletter-002.html), which has an [RSS feed](https://rust-gamedev.github.io/feed.xml) you can follow - that might be information overload if you just want to follow the WG rather than the ecosystem as a whole, though.

Using tags/releases is an interesting idea!

**Comment by Kinrany** [comment]
Oh, I'll use RSS then, thanks!

**Comment by Lokathor** [comment]
I'll close this up since things seem resolved.
