### ISSUE TITLE
Meeting: Dec 11, 2019

### ISSUE THREAD

**Issue by Lokathor** [rust-gamedev/wg#74]

**Comment by Lokathor** [comment]
Posted: https://www.reddit.com/r/rust/comments/e4qoxb/common_thread_pool_api/

Hopefully we'll get some good feedback.

**Comment by Lokathor** [comment]
https://github.com/rust-gamedev/wg/issues/75

**Comment by Lokathor** [comment]
Discussed https://github.com/TimDiekmann/alloc-wg again

**Comment by Lokathor** [comment]
https://github.com/rust-lang/wg-allocators

**Comment by msiglreith** [comment]
Input: State of OpenXR starting p. 25
https://www.khronos.org/assets/uploads/developers/library/2019-siggraph-asia/Khronos-Fast-Forward-SIGGRAPH-Asia_Nov19.pdf

**Comment by Wodann** [comment]
- Standardised API for sharing thread pools #75
  - @kabergstrom's approach is attended to share OS threads across multiple libraries
  - @msiglreith  proposes to have a simpler interface that leaves priority selection and time slotting to the user instead of the underlying crates
  - [Action] Collect requirements and use cases (champion: @Wodann)
  - [Action] Make a prototyping repo to try out proposed APIs that showcase the  aforementioned requirements and uses cases (champion: ?)
- Review action items of meeting Nov 27 (#70)
  - State of input handling
    - [Action] Create a "good first issue" to create an input mapping system from controller/kbm inputs to "actions" - inspired by SteamVR inputs & OpenXR. (champion: @wodann)

  - Allocator trait
    - @jaynus mentioned that their [purple allocator](https://github.com/rust-gamedev/wg/issues/71#issuecomment-554469478) uses the unstable `Alloc` trait
    - @jaynus will explore the alloc-wg traits to see how feel

- [Action] Ask @erlend-sh  whether the amethyst foundation would be interested in sponsoring the arewegameyet domains. (champion: @Wodann)
- [Action] Ask @erlend-sh whether we can help with the survey (champion: @Wodann)
- [Action] Final call to [add new members to wg](#73) (champion: @Wodann)
- [Action] Ask people what is a good time to hold the meeting in general to increase the number of people that consistently participate? (champion: @Lokathor)
- [Action] Ask people when is a good time to hold the next meeting, as it is in the Christmas week (champion: @Lokathor)
- [Action] Find out if we can contribute to the OpenXR spec by including KBM/controller (champion: ?)

**Comment by Lokathor** [comment]
The next meeting is on a currently unspecified day, but the issue is here: https://github.com/rust-gamedev/wg/issues/76

I think I've captured the gist of all the action items in the post there. Some of these I was able to do immediately, we already "have a repo" for the prototypes, people just need to make PRs and fill it up.

**Comment by Wodann** [comment]
Are you referring to the [wg](https://github.com/rust-gamedev/wg) repo?

**Comment by Lokathor** [comment]
Ah no! sorry I didn't post the link here as well (it's in the next meeting topic):

I opened this up
https://github.com/rust-gamedev/thread-pool-api-prototypes
So people can PR in prototypes and such.
